import {type NextPage} from "next";
import Head from "next/head";
import {SignOutButton, useUser} from "@clerk/nextjs";
import React, {useEffect} from "react";
import {useRouter} from "next/router";

const Home: NextPage = () => {
    const user = useUser()
    const router = useRouter()

    useEffect(() => {
        void router.push(user.isSignedIn ? 'home' : 'login')
    }, [user.isSignedIn])

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main
                className="flex flex-col">
                {user.isSignedIn && <SignOutButton/>}
            </main>
        </>
    );
};

export default Home;
